#!/usr/bin/env python3
"""
Appends Productivity, AI, Fintech, and Consumer benchmarks and generates liveDemos.ts
"""

import json
import os

productivity_list = [
    ("https://notion.so", "Notion", "Your connected workspace for docs, wikis, and projects", "Productivity & Knowledge Management", "Productivity",
     "An all-in-one connected workspace that unifies notes, documentation, project management, and generative AI into customizable Lego-like blocks.",
     "Knowledge workers, startup operators, project managers, students, and collaborative hybrid teams.",
     ["Primary: 'Get Notion free' (Direct workspace setup)", "Secondary: 'Request a demo' (Enterprise rollout path)", "AI hook: 'Try Notion AI' (AI writing and Q&A showcase)"],
     "Hero with iconic minimalist hand-drawn illustrations and dynamic UI canvas. Follows with 4 core product pillars (Docs, Wikis, Projects, Calendar), template gallery, and enterprise security certifications.",
     ["Used by over 30 million users and modern tech leaders (Figma, Ramp, Pixar, Headspace)", "Vibrant global creator community with thousands of shared templates", "SOC 2 Type II compliance and enterprise workspace governance"],
     "Warm, approachable, and intellectually empowering. Uses thoughtful phrasing like 'Think it. Build it.' and 'A home for your work.'",
     ["Blank canvas syndrome can intimidate beginners who do not know which template to start with", "Performance in deeply nested multi-database pages with thousands of relations"],
     ["Offer an interactive template picker quiz directly on the homepage matching specific team roles", "Provide a live interactive preview of Notion AI answering questions across a sample workspace"],
     "Notion's landing page is an editorial masterpiece of approachable software design. The combination of monochrome hand-drawn characters with rich modular UI mockups makes complex relational databases feel friendly and fun.",
     {"primary_segment": "Knowledge Workers, Product Teams & Startups", "monetization_model": "Freemium + Per-Seat Subscription + AI Add-on", "conversion_path": "Self-Serve Instant Workspace Creation", "design_signature": "Monochrome Line Art, Modular Block Previews, Pastel Badges"}),

    ("https://figma.com", "Figma", "How teams design & build modern digital products", "Design Tools & Collaboration", "Productivity",
     "The industry-standard collaborative interface design platform that unifies design, prototyping, design systems, and developer handoff in real time.",
     "Product designers, UI/UX engineers, design system leads, and cross-functional product squads.",
     ["Primary: 'Get started for free' (Browser-based canvas launch)", "Secondary: 'Explore Dev Mode' (Developer handoff demo)", "Enterprise: 'Contact sales' (Organization & Enterprise plan)"],
     "Hero featuring real-time multiplayer cursors hovering over dynamic vector UI components. Explains Design, Prototyping, Design Systems, Dev Mode, and FigJam collaborative whiteboard.",
     ["Universal standard across tech giants: Netflix, Spotify, Airbnb, Zoom, Microsoft", "Active Community Hub with millions of open-source design kits and plugins", "Browser-first WebAssembly performance with enterprise SOC 2 compliance"],
     "Energetic, creative, and collaborative. Emphasizes multiplayer synergy: 'Nothing great is made alone.'",
     ["Complexity of advanced auto-layout and variable modes can require dedicated training for new designers", "High memory usage on complex multi-thousand frame design files in browser tabs"],
     ["Add an interactive live Figma canvas in the hero where visitors can drag and resize components", "Include an interactive Dev Mode inspector showing instant CSS/Swift/Kotlin code generation"],
     "Figma's landing page radiates multiplayer energy. Floating colored cursors, playful micro-interactions, and vibrant primary colors celebrate the joy of collaborative product craftsmanship.",
     {"primary_segment": "Product Designers, UI Engineers & Cross-Functional Squads", "monetization_model": "Freemium + Per-Editor Tiered Subscription", "conversion_path": "Instant In-Browser Design Canvas Launch", "design_signature": "Multiplayer Cursors, Bold Color Blocks, Vector Handles"}),

    ("https://raycast.com", "Raycast", "Your shortcut to everything", "Productivity & Desktop Velocity", "Productivity",
     "An extendable, blazingly fast desktop launcher for macOS and Windows that replaces Spotlight with instant command execution, clipboard history, window management, and custom developer extensions.",
     "Power users, software engineers, designers, and keyboard velocity enthusiasts.",
     ["Primary: 'Download for Mac' (Direct DMG download)", "Secondary: 'Explore Store' (Thousands of community extensions)", "AI hook: 'Raycast AI' (System-wide LLM assistant)"],
     "Hero with deep dark mode palette and glowing command palette animation. Walks through core built-ins (Clipboard History, Window Management, Snippets, AI), Store extension ecosystem, and Developer API.",
     ["Cult-like following among elite Silicon Valley developers and designers", "Over 1,000+ community extensions built on Node.js/React APIs", "Native Swift performance with sub-10ms response times"],
     "Laser-focused on velocity, craft, and precision. Short, punchy, keyboard-centric copy: 'Supercharged productivity.'",
     ["macOS exclusive heritage (Windows version in rollout) limits immediate utility for pure PC enterprise fleets", "Keyboard shortcut mastery requires deliberate habit retraining away from mouse-driven menus"],
     ["Include an interactive web-based launcher demo where visitors can press hotkeys and run extensions", "Provide a 1-click migration guide for Alfred and Spotlight users"],
     "Raycast is the epitome of native desktop craft. Its dark cosmic aesthetic, glowing neon gradients, and extreme keyboard-driven velocity make everyday desktop computing feel modern.",
     {"primary_segment": "macOS Power Users, Developers & Designers", "monetization_model": "Free Personal + Pro AI Subscription + Team Shared Commands", "conversion_path": "Direct Desktop DMG Binary Download", "design_signature": "Deep Cosmic Slate, Glowing Command Palette, Hotkey Badges"}),

    ("https://miro.com", "Miro", "The visual workspace for innovation", "Visual Collaboration & Whiteboarding", "Productivity",
     "An infinite visual collaborative canvas that empowers distributed teams to brainstorm, map architectures, run agile ceremonies, and co-create product roadmaps.",
     "Product managers, UX researchers, agile coaches, strategy consultants, and distributed enterprise teams.",
     ["Primary: 'Sign up free' (Instant whiteboard canvas launch)", "Secondary: 'Request a demo' (Enterprise scale deployment)", "Template hook: 'Explore 300+ templates' (Pre-built frameworks)"],
     "Hero with expansive canvas diagram showing sticky notes, wireframes, and video call avatars. Showcases core use cases: Strategy & Planning, Diagramming, Agile Ceremonies, and Miro Assist AI.",
     ["Used by 99% of Fortune 100 companies and over 60 million users worldwide", "Extensive ecosystem with 100+ app integrations (Jira, Confluence, Figma, Slack)", "Enterprise-grade data residency, ISO 27001, and HIPAA compliance"],
     "Expansive, collaborative, and inclusive. Focuses on team alignment: 'Where great ideas become real.'",
     ["Infinite canvas can become disorganized without strict board facilitation and template governance", "Performance lag on extremely large enterprise canvases with thousands of visual objects"],
     ["Add an interactive mini-canvas on the homepage where visitors can drop sticky notes and vote", "Provide role-based interactive guided tours tailored for Product Managers vs Scrum Masters"],
     "Miro effectively communicates the feeling of an infinite physical whiteboard room. The bright yellow accents, playful cursor trails, and rich diagramming previews inspire collaborative creative confidence.",
     {"primary_segment": "Enterprise Product Teams, Agile Coaches & Strategy Leads", "monetization_model": "Freemium + Per-User Subscription (Starter/Business/Enterprise)", "conversion_path": "Self-Serve Interactive Canvas Creation", "design_signature": "Miro Yellow Accents, Infinite Grid, Sticky Note Clusters"}),

    ("https://loom.com", "Loom", "One video is worth a thousand words", "Async Video & Team Communication", "Productivity",
     "An asynchronous video messaging platform that lets knowledge workers record camera, screen, and audio instantly to share quick, context-rich updates with automatic AI summaries and transcripts.",
     "Remote & hybrid teams, product managers, engineers doing code reviews, customer support, and sales executives.",
     ["Primary: 'Get Loom for free' (Chrome extension / Desktop app install)", "Secondary: 'Loom for Enterprise' (Enterprise security path)", "Demo: 'Watch a Loom' (Interactive video player demo)"],
     "Hero with iconic circular webcam bubble floating over a screen recording. Walks through core use cases: Async Standups, Bug Reporting, Design Feedback, and Loom AI automated chapters and summaries.",
     ["Over 21 million users and 350,000 companies worldwide (Atlassian, Netflix, Disney, Tesla)", "Acquired by Atlassian for seamless Jira and Confluence integration", "SOC 2 Type II certified and enterprise SSO security"],
     "Human, empathetic, and time-respecting. Focuses on eliminating unnecessary meetings: 'Say it with video.'",
     ["Free tier 5-minute video limit and 25-video storage limit can trigger upgrade pressure quickly", "Camera anxiety for users unaccustomed to recording asynchronous video messages"],
     ["Include an interactive video player on the hero where visitors can experience Loom AI transcripts and emoji reactions live", "Provide a meeting time calculator showing hours saved per week by replacing standups with Looms"],
     "Loom's design centers around the friendly circular bubble avatar. With warm purple gradients and clean playback controls, it transforms intimidating screen recording into a warm, natural conversation.",
     {"primary_segment": "Remote Workers, Product Managers & Customer Support", "monetization_model": "Freemium + Per-Creator Monthly Subscription (Business/Enterprise)", "conversion_path": "1-Click Chrome Extension Install", "design_signature": "Loom Purple Gradient, Circular Camera Bubble, Waveform Badges"}),

    ("https://slack.com", "Slack", "Where work happens", "Team Communication & Enterprise Collaboration", "Productivity",
     "The leading channel-based messaging platform and digital headquarters that unifies team conversations, file sharing, workflows, audio huddles, and AI-powered enterprise search.",
     "Modern knowledge workers, enterprise IT leaders, startup teams, and remote organizations.",
     ["Primary: 'Try for free' (Instant team workspace creation)", "Secondary: 'Talk to sales' (Enterprise Grid consultation)", "Download: 'Download Desktop App' (Native client install)"],
     "Hero with interactive animation of channels, threads, and emoji reactions. Highlights Channel Organization, Canvas docs, Audio Huddles, Workflow Builder automation, and Slack AI search.",
     ["Over 200,000 paid customers including 77 of the Fortune 100", "Ecosystem of over 2,600 third-party app integrations", "Enterprise Grid architecture with strict HIPAA, FINRA, and FedRAMP compliance"],
     "Vibrant, conversational, and energetic. Focuses on team alignment, culture, and reducing email overload.",
     ["Notification overload and 'fear of missing out' (FOMO) in high-traffic enterprise workspaces", "Pricing can be steep for large organizations upgrading from free to Business+ tiers"],
     ["Add an interactive channel simulator showing how automated workflows connect to Jira and Salesforce", "Provide an ROI calculator measuring email reduction and meeting time saved"],
     "Slack's landing page is iconic for its cheerful aubergine and multicolor palette. It successfully balances corporate enterprise reliability with an approachable, human-centered work culture aesthetic.",
     {"primary_segment": "Global Enterprise Workplaces & Modern Startups", "monetization_model": "Freemium + Per-Active-User Tiered Subscription", "conversion_path": "Self-Serve Workspace URL Creation", "design_signature": "Aubergine Purple, Channel Hash Icons, Emoji Reaction Chips"}),

    ("https://coda.io", "Coda", "The all-in-one doc that brings words, data, and teams together", "Collaborative Docs & No-Code Apps", "Productivity",
     "A flexible canvas that blends the simplicity of a document with the computational power of a spreadsheet and database, letting teams build custom internal tools and workflows.",
     "Product leaders, operations managers, agile teams, and startup founders needing bespoke workflows.",
     ["Primary: 'Get started for free' (Workspace creation)", "Secondary: 'See how it works' (Interactive doc template demo)", "AI hook: 'Explore Coda AI' (In-doc AI assistant)"],
     "Hero featuring a living document that morphs into a full relational database app. Highlights Doc Maker community templates, Coda Packs (integrations with Figma, Jira, Slack), and Coda AI automations.",
     ["Used by teams at Uber, Spotify, Figma, The New York Times, and DoorDash", "Unique maker billing model (only pay for document creators, free for editors/viewers)", "SOC 2 Type II certified and enterprise workspace controls"],
     "Empowering, inventive, and maker-friendly. Challenges the artificial boundary between docs and applications.",
     ["Steeper learning curve for formula syntax and relational packs compared to basic text editors", "Performance can slow down on documents containing heavy cross-table calculations"],
     ["Include an interactive formula builder sandbox on the homepage demonstrating real-time data lookups", "Highlight Maker Billing calculator showing how many team members can edit for free"],
     "Coda uses energetic orange and purple gradients with clean interactive document widgets. It effectively proves that documents are no longer static digital paper, but living interactive software.",
     {"primary_segment": "Operations Leads, Product Managers & No-Code Builders", "monetization_model": "Maker Billing (Only pay for Doc Creators, Editors Free)", "conversion_path": "Instant Template Workspace Launch", "design_signature": "Coda Coral/Purple, Interactive Tables, Formula Tooltips"}),

    ("https://arc.net", "Arc Browser", "The browser reimagined for the modern internet", "Web Browser & Operating Environment", "Productivity",
     "A reimagined internet browser engineered by The Browser Company with vertical sidebar tabs, customizable Spaces, split view multitasking, and AI-powered browsing summaries.",
     "Designers, developers, students, researchers, and internet power users seeking a cleaner digital workspace.",
     ["Primary: 'Download Arc for Mac / Windows' (Instant installer download)", "Secondary: 'Meet Arc Search' (Mobile iOS app preview)", "Discovery: 'Explore Boosts' (Custom website styling)"],
     "Arresting artistic hero with smooth kinetic animations and vertical sidebar preview. Walks through Spaces (work/personal isolation), Split View, Little Arc quick look, and Arc Max AI features.",
     ["Winner of numerous design awards and beloved by tech innovators across Silicon Valley", "Built on Chromium engine for full Chrome extension compatibility", "Privacy-first model with zero tracking of user browsing history"],
     "Playful, poetic, and visionary. Treats internet browsing as an intimate personal experience rather than a utility.",
     ["Radical paradigm shift from traditional horizontal top tabs requires habit retraining", "Resource consumption on older laptop hardware with dozens of active Spaces"],
     ["Add an interactive web simulator where visitors can drag and organize vertical tabs and split views", "Provide a 1-click bookmarks and extension import preview from Google Chrome"],
     "Arc's website is a triumph of contemporary avant-garde web design. With fluid pastels, elegant typography, and micro-physics animations, it makes browsing the web feel magical and inspiring.",
     {"primary_segment": "Internet Power Users, Creatives, Developers & Students", "monetization_model": "100% Free Consumer Browser + Enterprise Arc for Teams", "conversion_path": "Direct Desktop Installer Download", "design_signature": "Pastel Mesh Gradients, Vertical Sidebar Layout, Kinetic Physics"}),

    ("https://obsidian.md", "Obsidian", "Sharpen your thinking with a second brain", "Personal Knowledge Management & Markdown", "Productivity",
     "A private, flexible, local-first note-taking app that stores notes as plain Markdown files on your device with bidirectional linking and an interactive 3D knowledge graph.",
     "Researchers, academics, software engineers, writers, and knowledge management enthusiasts.",
     ["Primary: 'Get Obsidian for Windows / macOS / Linux' (Direct installer download)", "Secondary: 'Explore Community Plugins' (Over 1,500+ open extensions)", "Add-on: 'Obsidian Sync & Publish' (Encrypted cloud sync)"],
     "Hero featuring a glowing constellation-like interactive knowledge graph. Highlights local-first plain text storage, bidirectional backlinks, canvas whiteboards, and extensive community themes.",
     ["100% user data ownership with zero cloud lock-in (plain Markdown files on disk)", "Thriving community with over 1,500+ plugins and 200+ themes", "End-to-end encrypted cloud synchronization option (Obsidian Sync)"],
     "Philosophical, durable, and uncompromising on privacy. Treats your notes as a lifelong digital asset.",
     ["Local-first architecture means mobile syncing requires Obsidian Sync or manual cloud folder setups", "Advanced customization (Dataview, CSS snippets) requires technical curiosity"],
     ["Include an interactive 3D knowledge graph in the hero where visitors can click and orbit connected notes", "Provide a plain-text future-proofing calculator comparing Markdown vs proprietary cloud notes"],
     "Obsidian's design is dark, focused, and cerebral. Its iconic purple crystal emblem and cosmic knowledge graphs celebrate deep personal reflection and sovereign data ownership.",
     {"primary_segment": "Researchers, Writers, Engineers & Knowledge Workers", "monetization_model": "Free Personal + Paid Encrypted Sync & Commercial Licenses", "conversion_path": "Direct Local Binary Install (No Account Required)", "design_signature": "Obsidian Crystal Purple, Interactive Node Graphs, Plain Text Focus"}),

    ("https://superhuman.com", "Superhuman", "The fastest email experience ever made", "Email Velocity & Executive Productivity", "Productivity",
     "An ultra-fast, keyboard-driven email client engineered to help founders, executives, and high-velocity teams achieve Inbox Zero in half the time with AI automated triage and draft synthesis.",
     "Founders, executives, venture capitalists, sales leaders, and professionals dealing with hundreds of emails daily.",
     ["Primary: 'Get Started' (VIP onboarding funnel with Gmail/Outlook connect)", "Secondary: 'Superhuman for Teams' (Team collaboration and shared snippets)", "AI hook: 'Superhuman AI' (Instant email drafting and summarization)"],
     "Hero featuring lightning-fast dark-mode email interface with 100ms response badge. Explains split inboxes, keyboard shortcuts, automated reminders, read status tracking, and Superhuman AI.",
     ["Cult following among tech leaders and Fortune 500 executives", "Over 1 billion emails processed with industry-leading sub-100ms interaction speed", "Built for Gmail and Microsoft Outlook enterprise environments"],
     "Luxurious, hyper-efficient, and uncompromising. Focuses on reclaiming precious hours of life: 'Fly through your inbox.'",
     ["Premium pricing ($30/month) represents a significant investment compared to free webmail", "Keyboard shortcut learning curve requires dedicated habit formation during initial onboarding"],
     ["Add an interactive in-browser simulation where visitors can experience 100ms keyboard navigation and Inbox Zero triage", "Provide an ROI calculator showing hours saved per year based on daily email volume"],
     "Superhuman represents high-luxury digital craftsmanship. Its deep velvet dark mode, polished gold accents, and obsessive typography deliver an unmistakable feeling of executive prestige.",
     {"primary_segment": "Executives, Founders, Sales Leaders & Power Users", "monetization_model": "Premium Monthly Subscription ($30/user/month)", "conversion_path": "Google / Microsoft OAuth Workspace Connection", "design_signature": "Velvet Dark Mode, Gold Foil Accents, 100ms Speed Badges"}),

    ("https://clickup.com", "ClickUp", "One app to replace them all", "Project Management & Collaboration", "Productivity",
     "An all-in-one productivity platform that consolidates tasks, docs, chat, goals, whiteboards, and time tracking into a single fully customizable workspace.",
     "Cross-functional teams, marketing agencies, software startups, and enterprises consolidating multiple SaaS tools.",
     ["Primary: 'Get Started' (Free forever with email signup)", "Secondary: 'Contact Sales' (Enterprise deployment path)", "AI hook: 'ClickUp Brain' (Connected neural network AI)"],
     "Vibrant hero featuring multi-view UI switcher (List, Board, Gantt, Calendar, Whiteboard). Showcases ClickUp Brain AI, custom dashboards, automated workflows, and tool replacement comparison grid.",
     ["Over 2 million teams and 10 million users worldwide (Netflix, Spotify, T-Mobile, IBM)", "Consolidates over 10 distinct point solutions into one subscription", "Enterprise SOC 2, HIPAA, ISO 27001, and GDPR compliance"],
     "Energetic, ambitious, and feature-rich. Emphasizes productivity gains and cost savings: 'Save one day every week.'",
     ["Massive feature density can lead to configuration paralysis without clear administrative setup", "Occasional UI loading latency on extremely large workspaces with hundreds of custom fields"],
     ["Include an interactive tool consolidator calculator where visitors can check off tools they currently pay for to see total annual savings", "Provide instant role-based workspace template setup"],
     "ClickUp uses vibrant neon gradients and high-energy illustrations. The landing page proves its 'one app to replace them all' promise through exhaustive interactive view switchers and tool comparison tables.",
     {"primary_segment": "Agencies, Cross-Functional Teams & Growing Startups", "monetization_model": "Freemium + Per-User Subscription (Unlimited/Business/Enterprise)", "conversion_path": "Instant Self-Serve Email Signup", "design_signature": "Multicolor Neon Gradients, Multi-View Toggles, High Density Cards"}),

    ("https://asana.com", "Asana", "Manage team projects, processes, and tasks", "Enterprise Work Management", "Productivity",
     "An enterprise work management platform that helps organizations orchestrate work across distributed teams, connect daily tasks to strategic company goals, and automate cross-functional processes.",
     "Enterprise operations leaders, marketing departments, PMOs, and distributed cross-functional organizations.",
     ["Primary: 'Get started' (Free trial signup)", "Secondary: 'See how it works' (Interactive workflow demo)", "Enterprise: 'Contact sales' (Enterprise plan consultation)"],
     "Clean, airy hero with dynamic project timeline visualization. Walks through Work Graph data model, Goal Tracking, Asana Intelligence AI, and Enterprise Security governance.",
     ["Used by over 150,000 paying organizations across 190 countries (Amazon, Roche, Affirm, Spotify)", "Named an enterprise Work Management leader by Gartner and IDC", "Enterprise-grade SOC 2 Type II, HIPAA, and ISO 27001 certifications"],
     "Empowering, structured, and clarity-driven. Focuses on eliminating confusion and aligning teams with executive goals.",
     ["Enterprise pricing tiers can feel expensive for small bootstrap startups", "Deep organizational workflows require enterprise buy-in and governance to maintain cleanliness"],
     ["Add an interactive Work Graph visualizer demonstrating how a task connects to team milestones and company OKRs", "Provide a pre-built marketing campaign workflow template simulator"],
     "Asana's landing page is an exemplar of serene, human-centered enterprise design. The soft coral accents, spacious layout, and dynamic timeline animations project organizational calm and executive clarity.",
     {"primary_segment": "Enterprise Organizations, PMOs & Marketing Teams", "monetization_model": "Freemium + Per-Seat Subscription (Starter/Advanced/Enterprise)", "conversion_path": "Self-Serve Workspace Creation & Enterprise Sales", "design_signature": "Asana Coral/Pastels, Work Graph Diagrams, Timeline Tracks"}),

    ("https://monday.com", "Monday.com", "The Work OS that powers team agility", "Work Management & Custom CRM", "Productivity",
     "A flexible cloud Work OS where teams build custom workflow apps and dashboards to manage projects, sales pipelines, software development, and marketing campaigns.",
     "Business operations managers, sales directors, project managers, and enterprise department heads.",
     ["Primary: 'Get Started' (Email signup without credit card)", "Secondary: 'Contact Sales' (Enterprise Work OS demo)", "Product suite: 'Explore monday dev, CRM, & Work Management' (Product selector)"],
     "Vibrant hero featuring interactive multi-color status cells. Walks through specialized products (Work Management, CRM, Dev, Service), automated triggers, and executive KPI reporting dashboards.",
     ["Over 225,000 customers worldwide across 200+ industries (Canva, Coca-Cola, Lionsgate, EA)", "Listed on NASDAQ with enterprise-grade multi-region cloud infrastructure", "Over 200+ out-of-the-box business workflow integrations"],
     "Dynamic, celebratory, and operational. Highlights colorful visual status boards and eliminating manual administrative work.",
     ["Minimum seat threshold on paid tiers can increase entry cost for tiny 2-person teams", "Broad modularity requires initial onboarding effort to configure optimal board columns"],
     ["Include an interactive board column builder directly in the hero where users can click status badges from 'In Progress' to 'Done'", "Provide a specialized product picker tailored to Marketing vs Sales vs Engineering"],
     "Monday.com is famous for its vibrant rainbow status tiles and playful celebratory micro-animations. It makes tracking operational tasks feel engaging, visual, and rewarding.",
     {"primary_segment": "Operations Managers, Sales Teams & Enterprise Departments", "monetization_model": "Per-Seat Tiered Subscription (Basic/Standard/Pro/Enterprise)", "conversion_path": "Instant Self-Serve Email Signup", "design_signature": "Vibrant Rainbow Status Tiles, Modular Product Badges, Clean Grids"}),

    ("https://basecamp.com", "Basecamp", "The refreshingly simple project management system", "Project Management & Remote Work", "Productivity",
     "A delightfully straightforward project management and team communication system designed to eliminate workplace chaos, endless meetings, and fragmented chat apps.",
     "Small business owners, remote agencies, bootstrapped startups, and teams seeking calm software.",
     ["Primary: 'Try Basecamp for Free' (30-day free trial, no credit card)", "Secondary: 'Pricing' (Transparent flat-rate pricing)", "Story: 'Read the Basecamp Way' (Remote work philosophy)"],
     "Warm, editorial hero with whimsical hand-drawn illustrations by Jason Fried. Highlights 6 core tools per project (Message Board, To-dos, Card Table, Schedule, Docs & Files, Campfire chat), and the legendary flat-rate pricing model.",
     ["Pioneers of remote work and creators of Ruby on Rails", "Over 20 years of continuous profitable software operation", "Trusted by millions of small businesses and boutique agencies around the world"],
     "Unfiltered, authentic, opinionated, and calm. Rejects corporate tech jargon in favor of honest human prose.",
     ["Lack of complex Gantt dependencies or deep enterprise time-tracking integrations is a deliberate philosophy that may not suit heavy PMOs", "Traditional flat project structure rather than infinite nested sub-tasks"],
     ["Include an interactive 'Before Basecamp vs After Basecamp' chaos-to-calm slider", "Highlight flat-rate pricing savings calculator for teams with 20+ members"],
     "Basecamp stands out as a beacon of independent software philosophy. Its hand-drawn line art, yellow paper accents, and warm editorial typography make project management feel human, peaceful, and grounded.",
     {"primary_segment": "Small Businesses, Agencies & Bootstrapped Startups", "monetization_model": "Per-User ($15/mo) OR Unlimited Flat-Rate ($299/mo)", "conversion_path": "30-Day Free Trial (No Credit Card Required)", "design_signature": "Hand-Drawn Editorial Art, Yellow Accents, Calm Typography"}),

    ("https://pitch.com", "Pitch", "Collaborative presentations engineered for modern teams", "Presentation Software & Storytelling", "Productivity",
     "A modern presentation platform that combines the creative flexibility of graphic design software with smart collaborative workflows, real-time analytics, and AI-assisted deck generation.",
     "Startup founders pitching investors, marketing teams, sales executives, and design agencies.",
     ["Primary: 'Start for free' (In-browser slide deck creation)", "Secondary: 'Explore templates' (Designer-curated presentation kits)", "AI hook: 'Generate a deck with AI' (Instant prompt-to-slides)"],
     "Hero featuring smooth interactive 3D slide transitions and typography specimen. Highlights collaborative slide editing, smart formatting that adapts to content, presenter analytics, and custom brand templates.",
     ["Used by leading tech companies (Grammarly, Notion, Superhuman, Maze)", "Curated library of over 100+ award-winning startup pitch decks and sales templates", "SOC 2 Type II certified and enterprise workspace governance"],
     "Sophisticated, design-forward, and storytelling-focused. Focuses on confidence and winning stakeholders.",
     ["Exporting to legacy PowerPoint (.pptx) can occasionally require minor typography adjustments", "Desktop client performance on very large decks with dozens of embedded 4K video clips"],
     ["Add an interactive slide editor in the hero where visitors can type text and watch auto-formatting adapt live", "Include an interactive pitch deck gallery featuring real Y Combinator pitch decks"],
     "Pitch is the Figma of presentation design. Its dark sleek canvas, gorgeous typography, and spring-physics slide transitions elevate pitch decks from boring slideshows into cinematic digital stories.",
     {"primary_segment": "Founders, Sales Directors, Marketers & Creative Teams", "monetization_model": "Freemium + Per-Member Subscription (Pro/Business)", "conversion_path": "Instant Web Canvas Slide Creation", "design_signature": "Cinematic Dark Canvas, 3D Slide Physics, Glowing Accents"}),

    ("https://canva.com", "Canva", "Design anything, publish anywhere", "Graphic Design & Visual Content Creation", "Productivity",
     "An intuitive visual communication platform that empowers non-designers and teams to create social media graphics, presentations, videos, marketing collateral, and print assets with drag-and-drop ease.",
     "Marketers, small business owners, educators, creators, and enterprise teams needing fast visual assets.",
     ["Primary: 'Start designing for free' (Instant canvas launch)", "Secondary: 'Try Canva Pro' (Brand Kit and background remover trial)", "Enterprise: 'Canva for Enterprise' (Enterprise brand controls)"],
     "Vibrant hero with animated design canvas showcasing templates morphing from Instagram posts to enterprise slide decks. Highlights Magic Studio AI, Brand Kits, video editing, and print-on-demand services.",
     ["Over 170 million monthly active users across 190 countries", "Millions of designer-curated templates, royalty-free photos, and vector assets", "Trusted by 85% of the Fortune 500 (Zoom, FedEx, Salesforce, Reddit)"],
     "Inspirational, empowering, and democratic. Celebrates creative expression: 'Empowering the world to design.'",
     ["Professional designers may find vector editing and typographic precision more constrained than Adobe Illustrator/Figma", "Export resolution limitations on free tier without Canva Pro subscription"],
     ["Include an interactive Magic Studio AI tool on the hero where visitors can type a prompt to generate a custom social graphic", "Provide a template finder filtered by exact industry and social platform dimensions"],
     "Canva's design is energetic, inclusive, and radiant. Its iconic cyan-to-purple gradient and joyful template carousels immediately dispel the intimidation of graphic design and invite everyone to create.",
     {"primary_segment": "Non-Designers, Marketers, Educators & Small Businesses", "monetization_model": "Freemium + Canva Pro / Canva for Teams Subscription", "conversion_path": "1-Click Instant Web Design Workspace", "design_signature": "Cyan-Purple Gradient, Template Carousels, Magic Sparkle Badges"}),

    ("https://craft.do", "Craft", "Create documents that inspire", "Document Design & Native Note-Taking", "Productivity",
     "A native document editor for Apple and Windows platforms that lets individuals and teams create visually stunning, structured documents with cards, media blocks, and instant web sharing.",
     "Designers, executives, agency owners, writers, and Apple ecosystem power users.",
     ["Primary: 'Get Craft for Free' (App Store and Desktop download)", "Secondary: 'Explore Craft for Teams' (Collaborative workspaces)", "Web: 'Open in Web' (Browser-based document editor)"],
     "Hero featuring breathtaking native document previews with nested card previews and custom covers. Highlights card styling, instant public share links, offline performance, and Craft AI Assistant.",
     ["Apple Design Award winner for exceptional craft and UI aesthetics", "Ultra-fast native Swift codebase on macOS, iOS, iPadOS, and Windows", "End-to-end cloud synchronization and offline-first reliability"],
     "Elegant, refined, and visually proud. Focuses on transforming boring black-and-white text into inspiring visual documents.",
     ["Relational database capabilities are lighter compared to Notion's heavy database schema builder", "Windows and Web apps continue evolving to match the deep polish of the native macOS app"],
     ["Add an interactive nested card expander directly in the hero showing document nesting", "Provide an instant document export preview to PDF and beautiful web pages"],
     "Craft is the pinnacle of native Apple design aesthetics. With translucent materials, exquisite typography, and nested card layouts, it proves that internal documents can be as beautiful as magazine editorials.",
     {"primary_segment": "Executives, Designers, Creative Agencies & Writers", "monetization_model": "Freemium + Per-User Pro / Team / Business Subscription", "conversion_path": "App Store Download & Web Workspace Launch", "design_signature": "Translucent Glass, Nested Document Cards, Editorial Serif Fonts"}),

    ("https://bear.app", "Bear", "Markdown notes for writers and thinkers", "Markdown Notes & Minimalist Writing", "Productivity",
     "A beautiful, focused Markdown writing application for Mac, iPad, and iPhone with nested tag organization, rich inline previews, and encrypted local storage.",
     "Writers, journalists, bloggers, developers, and minimalist note-takers within the Apple ecosystem.",
     ["Primary: 'Download on the Mac App Store' (Direct App Store link)", "Secondary: 'Download for iOS' (App Store link for iPhone/iPad)", "Features: 'Explore Markdown features' (Typography and tagging guide)"],
     "Serene hero featuring Bear's iconic red bear logo and crisp typography. Highlights typography themes, nested hashtag organization, encrypted notes, and instant Markdown export.",
     ["Apple Design Award winner and widely celebrated writing application", "Beloved by prominent authors, journalists, and software developers", "100% private iCloud synchronization with no third-party tracking"],
     "Peaceful, craft-focused, and distraction-free. Emphasizes the joy of raw writing without interface clutter.",
     ["Apple ecosystem exclusivity (macOS/iOS only) means no native Windows or Android support", "No multi-user real-time collaborative editing (focused strictly on individual writing)"],
     ["Include an interactive theme switcher on the hero showing Red Graphite, Solarized, and Dark Graphite themes", "Provide an interactive nested tag hierarchy explorer"],
     "Bear is a love letter to typography and minimalist writing. Its warm white space, iconic red accents, and custom font pairings create an inviting, distraction-free sanctuary for thought.",
     {"primary_segment": "Writers, Journalists, Developers & Apple Users", "monetization_model": "Free Local App + Inexpensive Bear Pro iCloud Sync ($2.99/mo)", "conversion_path": "Mac App Store 1-Click Install", "design_signature": "Bear Crimson Red, Clean White Space, Typography Themes"}),

    ("https://framer.com", "Framer", "Design and publish stunning websites in seconds", "No-Code Web Design & Publishing", "Productivity",
     "A website design tool that combines the intuitive freeform canvas of Figma with production-ready responsive layout, spring animations, CMS, and instant 1-click publishing to the edge.",
     "Product designers, web agencies, startup founders, and freelancers building high-end landing pages.",
     ["Primary: 'Start for free' (In-browser web canvas launch)", "Secondary: 'Explore templates' (Designer landing page templates)", "Community: 'Framer Community' (Shared components and plugins)"],
     "Hero featuring a living website canvas being manipulated in real time with interactive hover effects. Highlights Figma-to-Framer copy-paste, 60fps spring animations, built-in CMS, and sub-second edge hosting.",
     ["Powers landing pages for top startups and creators worldwide", "Built-in localization, SEO optimization, and global CDN hosting", "Figma plugin for instant 1-click design-to-live-site conversion"],
     "Fast, expressive, and visually ambitious. Emphasizes zero-compromise design freedom: 'Ship your dream site.'",
     ["Custom backend database logic and user authentication require third-party integrations (Supabase/Auth0)", "Complex responsive breakpoint layouts require understanding of flexbox and fixed sizing"],
     ["Include an interactive animation playground in the hero where visitors can adjust spring physics sliders", "Provide an instant Figma-to-Framer component paste preview"],
     "Framer represents the cutting edge of contemporary web design tools. Its dark mode interface, glowing spring physics visualizations, and instant live preview prove that designing and building websites can be the exact same creative act.",
     {"primary_segment": "Product Designers, Web Agencies & Freelancers", "monetization_model": "Freemium + Per-Site Hosting Subscription (Mini/Basic/Pro)", "conversion_path": "Self-Serve In-Browser Web Canvas", "design_signature": "Deep Obsidian Canvas, Spring Physics Curves, Live Breakpoints"}),

    ("https://cron.com", "Notion Calendar", "The next-generation calendar for professionals", "Time Management & Calendar Scheduling", "Productivity",
     "A modern, beautifully designed calendar and scheduling tool that integrates directly with Google Calendar, Notion databases, and meeting workflows to bring control and speed to your schedule.",
     "Busy professionals, founders, engineers, and Notion power users.",
     ["Primary: 'Get Notion Calendar for Free' (Direct Google Calendar auth)", "Secondary: 'Download Desktop App' (macOS and Windows native client)", "Integration: 'Connect with Notion' (Docs and database link)"],
     "Hero showcasing dark-mode calendar grid with smooth keyboard navigation and embedded Notion doc links. Highlights time blocking, multiple timezone overlays, built-in scheduling links, and native global hotkeys.",
     ["Originally developed as Cron (acquired by Notion and winner of Golden Kitty Award)", "Native integration across Notion workspaces and Google Calendar", "Ultra-smooth 60fps performance with comprehensive keyboard shortcuts"],
     "Precise, time-respecting, and minimalist. Focuses on taking back control of your day: 'Master your time.'",
     ["Currently requires Google Calendar account (Microsoft Outlook enterprise support in rollout)", "Keyboard shortcut conventions require brief familiarization for traditional mouse users"],
     ["Add an interactive timezone slider on the hero showing multi-city scheduling", "Include an interactive Notion database event sync simulation"],
     "Notion Calendar (formerly Cron) is a masterpiece of grid ergonomics. Its sleek dark interface, subtle hour rules, and keyboard shortcut velocity transform the dreaded calendar into a calm cockpit for deep work.",
     {"primary_segment": "Founders, Knowledge Workers & Notion Ecosystem Users", "monetization_model": "100% Free with Notion Ecosystem Integration", "conversion_path": "1-Click Google Calendar Authentication", "design_signature": "Precision Time Grids, Multi-Timezone Rails, Sleek Dark Slate"})
]

print(f"Productivity items: {len(productivity_list)}")
